local Router = {}
Router.__index = Router

function Router.new(services, import)
	local self = setmetatable({
		Result = import("Core/Result"),
		routes = {},
	}, Router)

	self:register("get_runtime_capabilities", function(params)
		return services.scripts:capabilities(params)
	end)
	self:register("get_instance_tree", function(params)
		return services.instances:getTree(params)
	end)
	self:register("get_instance_children", function(params)
		return services.instances:getChildren(params)
	end)
	self:register("find_instances", function(params)
		return services.instances:find(params)
	end)
	self:register("get_instance_properties", function(params)
		return services.properties:getProperties(params)
	end)
	self:register("read_instance_property", function(params)
		return services.properties:readProperty(params)
	end)
	self:register("list_scripts", function(params)
		return services.scripts:list(params)
	end)
	self:register("get_script_bytecode", function(params)
		return services.scripts:bytecode(params)
	end)
	self:register("decompile_script", function(params)
		return services.scripts:decompile(params)
	end)
	self:register("get_script_hash", function(params)
		return services.scripts:hash(params)
	end)
	self:register("get_script_environment", function(params)
		return services.scripts:environment(params)
	end)
	self:register("get_script_closure_info", function(params)
		return services.scripts:closureInfo(params)
	end)
	self:register("get_calling_script", function(params)
		return services.scripts:callingScript(params)
	end)
	self:register("get_runtime_logs", function(params)
		return services.runtime:getRuntimeLogs(params)
	end)
	self:register("tail_runtime_logs", function(params)
		return services.runtime:tailRuntimeLogs(params)
	end)
	self:register("watch_instance_changes", function(params)
		return services.watches:watchInstanceChanges(params)
	end)
	self:register("trace_signal_activity", function(params)
		return services.watches:traceSignalActivity(params)
	end)
	self:register("get_client_snapshot", function(params)
		return services.runtime:getClientSnapshot(params)
	end)
	self:register("get_memory_stats", function(params)
		return services.runtime:getMemoryStats(params)
	end)
	self:register("get_remote_overview", function(params)
		return services.runtime:getRemoteOverview(params)
	end)
	self:register("trace_remote_traffic", function(params)
		return services.watches:traceRemoteTraffic(params)
	end)
	self:register("get_tagged_instances", function(params)
		return services.runtime:getTaggedInstances(params)
	end)
	self:register("watch_tagged_instances", function(params)
		return services.watches:watchTaggedInstances(params)
	end)
	self:register("get_script_constants", function(params)
		return services.advanced:getScriptConstants(params)
	end)
	self:register("get_script_upvalues", function(params)
		return services.advanced:getScriptUpvalues(params)
	end)
	self:register("get_script_stack", function(params)
		return services.advanced:getScriptStack(params)
	end)
	self:register("search_gc_objects", function(params)
		return services.advanced:searchGcObjects(params)
	end)
	self:register("list_signal_connections", function(params)
		return services.advanced:listSignalConnections(params)
	end)
	self:register("read_hidden_property", function(params)
		return services.advanced:readHiddenProperty(params)
	end)
	self:register("is_property_scriptable", function(params)
		return services.advanced:isPropertyScriptable(params)
	end)
	self:register("find_nil_instances", function(params)
		return services.advanced:findNilInstances(params)
	end)
	self:register("get_streaming_diagnostics", function(params)
		return services.runtime:getStreamingDiagnostics(params)
	end)
	self:register("capture_screenshot", function(params)
		return services.runtime:captureScreenshot(params)
	end)
	self:register("get_service_overview", function(params)
		return services.runtime:getServiceOverview(params)
	end)
	self:register("diff_instance_snapshot", function(params)
		return services.watches:diffInstanceSnapshot(params)
	end)
	self:register("execute_luau", function(params)
		return services.executor:execute(params)
	end)

	return self
end

function Router:register(action, handler)
	assert(type(action) == "string" and action ~= "", "action must be a non-empty string")
	assert(type(handler) == "function", "handler must be a function")
	self.routes[action] = handler
end

function Router:dispatch(action, params)
	local handler = self.routes[action]
	if not handler then
		return self.Result.error("unknown_action", "Unknown bridge action: " .. tostring(action))
	end
	local ok, result = xpcall(function()
		return handler(params or {})
	end, function(err)
		if debug and debug.traceback then
			return debug.traceback(tostring(err), 2)
		end
		return tostring(err)
	end)
	if not ok then
		return self.Result.error("handler_error", tostring(result))
	end
	return result
end

return Router
